# Use the stable version of the lightweight Nginx image based on Alpine Linux
FROM nginx:stable-alpine
# Copy the custom index.html file to the default location served by Nginx
COPY index.html /usr/share/nginx/html/index.html
