version: "3.8"
services:
  weather-wrapper:
    build: .
    ports:
      - "8080:80"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - weather-wrapper
