# Exposes the frontend app via NodePort 30081 to external traffic.
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
spec:
  type: NodePort
  selector:
    app: weather-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
