# Frontend Deployment for Kubernetes.
# 1 replica 1 container based on img 'rudinaimeri/weather-frontend:latest'.
# Port 80 exposed container for static frontend.
# 'selector'for the deployment to manage only 'app: weather-frontend' marked units.
# monitoring, restarting and maintenance of the pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
      - name: weather-frontend
        image: rudinaimeri/weather-frontend:latest
        ports:
        - containerPort: 80
