# Exposes the weather-wrapper (backend) service on NodePort 30080 for external access.
apiVersion: v1
kind: Service
metadata:
  name: weather-wrapper
spec:
  type: NodePort
  selector:
    app: weather-wrapper
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
